CruiseManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include(('mainApp.urls','mainApp'), namespace = 'mainApp')),
]

mainApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^weather/$', views.weather, name='weather'),
    url(r'^songs/$', views.songs, name='songs'),
    url(r'^map/$', views.map, name='map'),
]

mainApp/models.py
from django.db import models

class Spot(models.Model):
    spotName = models.CharField(max_length = 200)
    coordinates = models.CharField(max_length = 50)

    def __str__(self):
        spotCoordinates = " (" + self.coordinates + ")"
        spotVerbose = self.spotName + spotCoordinates
        return spotVerbose

class Song(models.Model):
    songName = models.CharField(max_length = 200)
    songText = models.TextField()

    def __str__(self):
        return self.songName[:20] + "..."

mainApp/views.py
from django.shortcuts import render
import requests
from django.http import Http404, HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from .models import Spot,Song

from . import weatherAPI

def index(request):
    spots = Spot.objects.order_by('spotName')
    names = list()
    coordinates = list()
    for spot in spots:
        names.append(spot.spotName)
        coordinates.append(spot.coordinates)
    data = zip(names,coordinates)
    context = {'data':data}
    return render(request, 'mainApp/index.html',context)


def weather(request):
    if request.method == 'GET':       
        try:
            coordinates = request.GET['coordinates']
        except MultiValueDictKeyError:
            raise Http404
        
        if weatherAPI.isValidCoordinates(coordinates):
            try:
                ans = weatherAPI.getAPIresponse(coordinates)
                timestamps = weatherAPI.getTimestamps(ans)
                temperatures = weatherAPI.getTemperatures(ans)
                windSpeeds = weatherAPI.getWindSpeed(ans)
                beauforts = weatherAPI.knotsToBeaufort(windSpeeds)
                windDirections = weatherAPI.getWindDirection(ans)
                windDirectionsVerbosed = weatherAPI.verboseWindDirection(windDirections)
                plotURI = weatherAPI.getPlot(timestamps,temperatures,windSpeeds)
            except KeyError:
                 responseString = "Niewłaściwe współrzędne!<br>Wpisz współrzędne w postaci: <i>d.ddd...ddd,d.ddd...ddd</i> (stopnie miaromierne)."
                 return HttpResponse(responseString)
            
            spots = Spot.objects.order_by('spotName')
            spotsNames = list()
            spotsCoordinates = list()
            
            for spot in spots:
                spotsNames.append(spot.spotName)
                spotsCoordinates.append(spot.coordinates)

            if coordinates in spotsCoordinates:
                for i in range(len(spotsNames)):
                    if spotsCoordinates[i] == coordinates:
                        spotName = spotsNames[i]
                        context = {'spotName':spotName,'data':zip(timestamps,temperatures,windSpeeds,beauforts,windDirections,windDirectionsVerbosed),'plot':plotURI}
            else:
                spotName = coordinates
                context = {'spotName':spotName,'data':zip(timestamps,temperatures,windSpeeds,beauforts,windDirections,windDirectionsVerbosed),'plot':plotURI}
            
            return render(request, 'mainApp/weather.html', context)
        else:
            responseString = "Niewłaściwe współrzędne!<br>Wpisz współrzędne w postaci: <i>d.ddd...ddd,d.ddd...ddd</i> (stopnie miaromierne)."
            return HttpResponse(responseString)

def songs(request):
    songs = Song.objects.order_by('songName')
    titles = list()
    texts = list()
    
    for song in songs:
        titles.append(song.songName)
        texts.append(song.songText)
    data = zip(titles,texts)
    context = {'titles':titles,'data':data}
    return render(request, 'mainApp/songs.html', context)

def map(request):
    return render(request, 'mainApp/map.html')

mainApp/templates/mainApp/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="pl">

  <head>
    <meta charset="utf-8">
    <meta http-equiq="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Rejs na Mazury</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>

    <nav class="navbar-header">
      <a class="navbar-brand" href="{% url "mainApp:index" %}">Strona główna</a>
    </nav>  

    <div class="container">
  
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
     </div>

    </div>

    <footer>
      <div class="footer-copyright text-center py-3">
        Author: Bartosz Łukasik
        <a href="https://github.com/bartek-krk/CruiseManager">GitHub</a>
      </div>
   </footer>

  </body>
</html>

mainApp/templates/mainApp/index.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="pl">

  <head>
    <meta charset="utf-8">
    <meta http-equiq="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Rejs na Mazury</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body> 

    <div class="container">
      <div class="page-header">
          <div class="jumbotron">
            <h1>Witaj na stronie rejsu na Mazury</h1>
          </div>
      </div>
      
    <div>
      <h2>Sprawdź prognozę pogody w popularnych lokalizacjach lub wpisz współrzędne</h2>
      <ul>
        {% for item in data %}
          <li><a href="{%url 'mainApp:weather' %}?coordinates={{ item.1 }}">{{ item.0 }}</a></li>
        {% endfor %}
        <li>
          <form action="{%url 'mainApp:weather' %}" method="get">
            <label>Współrzędne:</label>
            <input type="text" name="coordinates" value="0,0">
            <input type="submit" value="Wyszukaj prognozę"><br>
            <label>Używaj stopni miaromiernych.</label>
          </form>
        </li>
      </ul>

       <h2><a href="{%url 'mainApp:songs' %}">Śpiewnik</a></h2>
       <h2><a href="{% url 'mainApp:map' %}">Mapa rejsu</a></h2>

      </div>

    </div>

    <footer>
      <div class="footer-copyright text-center py-3">
        Author: Bartosz Łukasik
        <a href="https://github.com/bartek-krk/CruiseManager">GitHub</a>
      </div>
   </footer>

  </body>
</html>

mainApp/templates/mainApp/map.html
{% extends "mainApp/base.html" %}
{% include "mainApp/navbar.html" %}

{% block navbar %}{% endblock navbar %}

{% block header %}
  <div class="jumbotron">
    <h1>Mapa rejsu</h1>
  </div>
{% endblock header %}

{% block content %}
  <iframe src="https://www.google.com/maps/d/embed?mid=1o4tb5npFkzgpQIWz8E9KCmvAH96DChm8" width=100% height="400"></iframe>
{% endblock content %}

<footer>
  <div class="footer-copyright text-center py-3">
    Author: Bartosz Łukasik
    <a href="https://github.com/bartek-krk/CruiseManager">GitHub</a>
  </div>
</footer>

mainApp/templates/mainApp/songs.html
{% extends "mainApp/base.html" %}

{% block header %}

  <div class="jumbotron">
    <h1>Śpiewnik</h1>
    <ol>
      {% for title in titles %}
        <li><a href="#{{ forloop.counter }}">{{ title }}</a></li>
      {% endfor %}
   </ol>
  </div>

{% endblock header %}

{% block content %}

  {% for item in data %}
    <div class="panel panel-default">
      <h2 id={{ forloop.counter }}>{{ item.0 }}</h2>
      <p>{{ item.1|linebreaks }}</p>
    </div>
  {% endfor %}

{% endblock content %}

mainApp/templates/mainApp/weather.html
{% extends "mainApp/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Prognoza pogody dla: {{  spotName }}</h1>
  </div>
{% endblock header %}

{% block content %}
  <img src="data:image/png;base64,{{ plot }}" class="img-responsive center-block" alt="Wykres pogodowy">

  <table class="table table-bordered">
    <th>Czas</th>
    <th>Temperatura [&degC]</th>
    <th>Prędkość wiatru [kn. (&degB)]</th>
    <th>Kierunek wiatru</th>
    {%for i in data %}
      <tr>
        <td>{{ i.0 }}</td>
        <td>{{ i.1 }}</td>
        <td>{{ i.2 }} ({{ i.3 }})</td>
        <td>{{ i.4 }}&deg ({{ i.5 }})</td>
      </tr>
    {% endfor %}
 </table>

{% endblock content %}